name: Deploy

concurrency: production

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build & deploy
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18.x]
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
        environment:
            name: solfa20.akfgfragments.com
            url: https://solfa20.akfgfragments.com
        
        steps:
            - name: Chekout the repo
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: "npm"

            - name: Install dependencies
              run: npm i

            - name: Build
              run: npm run build

            - run: mkdir ~/.ssh

            - run: echo "$SSH_KEY" >> ~/.ssh/github-action
            
            - run: chmod 400 ~/.ssh/github-action
            
            - run: echo -e "Host vps\n\tUser ${{ secrets.USER }}\n\tHostname ${{ secrets.IP }}\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
            
            - run: rsync -re ssh ./.next/ vps:${{ secrets.PATH }}/.next
            
            - run: ssh vps "pm2 restart solfa20"