name: Build & deploy

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  copy:
    name: Copy files
    runs-on: ubuntu-latest
        
    steps:
      - name: Chekout the repo
        uses: actions/checkout@v4
        
      - name: Load to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: ${{ secrets.PATH }}
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}
  
  build:
    name: Build the code on the server
    runs-on: ubuntu-latest

    environment:
      name: solfa20.akfgfragments.com
      url: https://solfa20.akfgfragments.com

    steps:
      - name: Create .env file
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.PATH }}; touch .env; echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env; echo "URL=${{ secrets.URL }}" >> .env
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}
      
      - name: Build and restart the app on the server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.PATH }}; npm i; npm run deploy
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_KEY }}